### ISSUE TITLE
Main demo is broken/incomplete

### ISSUE THREAD

**Issue by tiberiucorbu** [skidding/dragdealer#107]
From the main doc : 

![image](https://cloud.githubusercontent.com/assets/1186522/10717518/05c4cb16-7b5b-11e5-8aee-58b46053c090.png)

Presumably one can understand that this code should work fine :

### HTML :

    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>JS Bin</title>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/dragdealer/0.9.8/dragdealer.min.js"></script>
    </head>
    <body>
    <div id="demo-simple-slider" class="dragdealer">
      <div class="handle red-bar">drag me</div>
    </div>
    </body>
    </html>

### JS 

    new Dragdealer('demo-simple-slider');

Demo here http://jsbin.com/qepakijola/edit?html,js,output

But it doesn't, one needs also the style, so please point that out too!

**Comment by skidding** [comment]
Good point. I think it has more to do with the [install README section](https://github.com/skidding/dragdealer#install) than the demo page, though. Feel free to come up with a PR to update the instructions with CSS included. Thanks!
