### ISSUE TITLE
How to disable point to scroll outside the handle?

### ISSUE THREAD

**Issue by marcocastignoli** [skidding/dragdealer#119]
I want to put some content in the handle container, but when i tap on my content the handle starts sliding to the point I clicked. Is there an option to disable this?

**Comment by marcocastignoli** [comment]
I implemented it:

scrollToTap

```
onWrapperMouseDown: function(e) {
      if (!this.options.scrollToTap) {
          return;
      }
      Cursor.refresh(e);
      preventEventDefaults(e);
      this.startTap();
  },
```

**Comment by skidding** [comment]
Cool!

**Comment by marcocastignoli** [comment]
Are you sarcastic? There was already another feature like this?

**Comment by skidding** [comment]
> There was already another feature like this?

No.

Not sarcastic. Happy you found a solution so quick. Feel free to create a PR to make it an official option.
