### ISSUE TITLE
filtering out spurious mouseMove preventing mouseClick in Chrome

### ISSUE THREAD

**Issue by g-van-vreckem** [skidding/dragdealer#58]
There is a problem with the current version of Chrome:
It very often emits mouseMouve event after the mouseDown event and before the mouseUp but with no user mouse movement (big killing bug!).
In this case, this should restore the click functionality, while being transparent for browser with no e.movementX support.

```javascript
  onDocumentMouseMove: function(e) {
    Cursor.refresh(e);
    if (this.dragging) {
	  if( !this.activity && e.movementX === 0 && e.movementY === 0 ) return;
      this.activity = true;
    }
  },
```

**Comment by skidding** [comment]
I wouldn't optimize for Chrome bugs. Can you please let us know if this is still an issue?
