### ISSUE TITLE
enable vertical and horizontal swipe [question]

### ISSUE THREAD

**Issue by chris-Kwan** [skidding/dragdealer#71]
Hi Ovidiu,

Dragdealer is amazing. Thank you for your work and all the intuitive demos. 

I have a question. Since I am new to javascript, it might be a stupid one.
I am trying to use Dragdealer to create a simple game, where the user can swipe up, down, right and left to modify the background image shown in a wrapper. So is it possible to achieve this effect by extending the carousel demo?  Can you give me a hint? Thank you very much.

with regards,
Chris

**Comment by skidding** [comment]
It's the last demo what you're looking for? See "Interactive canvas mask" at the bottom: http://skidding.github.io/dragdealer/

**Comment by chris-Kwan** [comment]
hello Ovidiu,

Thank you very much for your reply.
I would like to change the background image entirely by reacting to both horizontal and vertical swipes.
I have managed to write a new library based on your implementation. So I have a matrix of images that can be manipulated.

Br,

Wei

**Comment by skidding** [comment]
From your last message I understand you've managed to find a solution to your problem, so I'm closing this.

Cheers!
