### ISSUE TITLE
jquery

### ISSUE THREAD

**Issue by brody182** [skidding/dragdealer#78]
can you make this in jquery?

**Comment by tiesont** [comment]
Not sure what you mean. If you're asking for a re-write, I doubt that's going to happen. If you're looking to abstract Dragdealer behind a jQuery function, you can always do something like:
```
$.fn.dragDealer = function (options) {
	var _this = $(this);
	
	new Dragdealer(_this.get(0), options);
};
```
which would let you use this:
````
$('#some-valid-id').dragDealer({
    steps: 4,
    speed: 0.3,
    // etc.
});
````
If you wanted to be able to initialize multiple sliders, you'd want to wrap the inner bits in an `each()`, which might look like:
```
$.fn.dragDealer = function (options) {
	this.each(function(index, elem){
		var _this = $(this);
	
		new Dragdealer(_this.get(0), options);
	});
};
```
This is all completely untested, so it'd be up to you to discover any caveats.

**Comment by brody182** [comment]
this is close, I want to integrate( touch-ready image carousel.) with jquery slider

new Dragdealer('image-carousel', {
  steps: 4,
  speed: 0.3,
  loose: true,
  requestAnimationFrame: true
});

**Comment by tiesont** [comment]
May I ask why? I assume you're referring to https://jqueryui.com/slider/, which has a lot of overlap (functionally) with Dragdealer. If you just want the look of the jQuery UI slider, you can get that by either inspecting the generated elements with something like Firebug, or by digging into the CSS of whatever theme you're using.

**Comment by skidding** [comment]
Closing this because the Dragdealer's mission was to be framework-agnostic from the beginning.
