### ISSUE TITLE
Reset and loop

### ISSUE THREAD

**Issue by DDROTT** [skidding/dragdealer#79]
Hello,

I want to reset my dragdealer image slider by scroll down. When I scroll down - I want to reset slider to first slide. I have multiple sliders and I want to reset them when scroll to next slider, so when I scroll back to that slider - I arrive at first slide instead of last slide where I've been.

Also, is it possible to go to first slide again after reaching the last slide?

Thank you.

**Comment by skidding** [comment]
Setting up the scroll listener and deciding *when* you want to reset the handler is up to you. Here is an example: http://stackoverflow.com/questions/14283205/jquery-window-scrolling-event

Once you decide to reset you can just call `.setValue(0, 0)` on your Dragdealer instance.

**Comment by DDROTT** [comment]
Thank You!
Is this code ok?

<script type="text/javascript">
    $(function(){
      $(window).scroll(function(){
        .setValue(0, 0)
      });
    });
  </script>

Can you help me with placing and editing this code?

Thank you.

**Comment by skidding** [comment]
> Can you help me with placing and editing this code?

Don't know what code you're referring to

**Comment by skidding** [comment]
Closing this because the topic is too ambiguous.
