### ISSUE TITLE
`{ x: 0.5, y: 0.5 }` doesn't center correctly in Safari

### ISSUE THREAD

**Issue by flovan** [skidding/dragdealer#80]
Hi,

It seems that the following does not center a draggable image in Safari (8.0.4, OS X Yosemite), while it does in Chrome, Firefox and Opera:

````javascript
var modalDD = new Dragdealer($modal.find('.image-embed')[0], {
	x: 0.5,
	y: 0.5,
	vertical: true,
	loose: true,
	speed: 0.3,
	requestAnimationFrame: true
});
````

My HTML looks like this:

````html
<div class="modal" data-type="image">
	<button class="close-btn modal__close-button"><svg role="img" title="Close"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#cross"></use></svg></button>
	<div class="image-embed dragdealer">
		<div class="image-embed__drag-label">Drag image to move</div>
		<img class="handle" src="http://localhost:8888/adagio/nominum/wp-content/uploads/2015/04/n2-targeting-screenshot-1024x659.jpg">
	</div>
</div>
````

Chrome gives the following inline styling:
````html
style="perspective: 1000px; backface-visibility: hidden; transform: translateX(120px) translateY(152px);"
````

While Safari outputs this:
````html
style="-webkit-perspective: 1000px; -webkit-backface-visibility: hidden; -webkit-transform: translateX(850px) translateY(477px);"
````

I'll try to find out where this bug occurs and if I do, I'll send you a PR.

**Comment by skidding** [comment]
@flovan does this still reproduce?

I tested on Safari `8.0.6` and everything seemed fine.

![dragdealer-safari](https://cloud.githubusercontent.com/assets/250750/7551213/2ad019a8-f689-11e4-9087-b158205775f7.gif)

**Comment by flovan** [comment]
The site demos work just fine. It was my particular setup that seemed to break things. The feature I was using dragdealer for got removed (luckily/unfortunately?), so this is no longer an issue for me.

I guess if you can't reproduce, than it was probably something on my end. Feel free to close!

**Comment by skidding** [comment]
OK. Let us know if you experience something similar in the future. Thanks!
