### ISSUE TITLE
looping the image when I drag last image

### ISSUE THREAD

**Issue by smartkid77** [skidding/dragdealer#81]
Hi.. I want to make a slider like 360degree, I made a simple drag slider using 1st example it works fine, But my requirement is when I drag a last image it ends there. I dont want it to be ended there, instead of that I want to drag the 1st image like loop.

Please can you help me.. I am so struggle with this issue. 

Thanks & Regards
Dina

**Comment by skidding** [comment]
An infinite carousel is outside the scope of Dragdealer and it would require a major rewrite to accommodate this use case.

I made such a carousel a few years ago, check out the source[1] for inspiration and the demo[2].
1. https://github.com/skidding/simple-carousel
2. http://skidding.github.io/simple-carousel
