### ISSUE TITLE
Dragdealer infinite image carousel

### ISSUE THREAD

**Issue by sibinx7** [skidding/dragdealer#82]
Sir

Dragdealer is am amazing plugin, but still it misses something..If you can add infinite image carousel it will be a good thing. Can you give an example to change it as infinite image carousel 

Thanks in advance

**Comment by skidding** [comment]
An infinite carousel is outside the scope of Dragdealer and it would require a major rewrite to accommodate this use case. Closing this.

I made such a carousel a few years ago, you can check out the source[1] for inspiration and the demo[2].

1. https://github.com/skidding/simple-carousel
2. http://skidding.github.io/simple-carousel
