### ISSUE TITLE
Differences between npm & github versions

### ISSUE THREAD

**Issue by ayamflow** [skidding/dragdealer#90]
Seems like both are `0.9.8` but npm's version doesn't have the `dragStartCallback` thing.
Are they out of sync?

**Comment by skidding** [comment]
npm is `0.9.8` but master HEAD is unreleased. There are [a few issues that were merged since 0.9.8 was published](https://github.com/skidding/dragdealer/compare/0.9.8...master)

**Comment by skidding** [comment]
You can use `"dragdealer": "git://github.com/skidding/dragdealer"` inside package.json dependencies to get latest HEAD until a new version is published.

**Comment by ayamflow** [comment]
Great :+1:

**Comment by NAlbuquerque** [comment]
Ovidiu, do have an eta on updating the NPM version?

**Comment by skidding** [comment]
@NAlbuquerque I'll try my best to push it this weekend, included with #103

**Comment by NAlbuquerque** [comment]
Awesome, thanks man!

**Comment by skidding** [comment]
Done. npm package is up to date: https://www.npmjs.com/package/dragdealer
