### ISSUE TITLE
Add dragdealer to bower

### ISSUE THREAD

**Issue by JuhQ** [skidding/dragdealer#92]
There has been a pull request on the matter here #27 and #30 but dragdealer as of now can't be found from bower.

```
$  bower install dragdealer
bower                        ENOTFOUND Package dragdealer not found
```

**Comment by skidding** [comment]
![image](https://cloud.githubusercontent.com/assets/250750/8272758/7eeef8ba-1858-11e5-8356-642cc0bf4e06.png)

What about now?

**Comment by JuhQ** [comment]
:+1: works!
