### ISSUE TITLE
dragStartCallback / dragStopCallback not working?

### ISSUE THREAD

**Issue by thiagocoelho** [skidding/dragdealer#96]
Hi,

I'm not sure if I missed something but looks like those events aren't working.

This is my code:

```
    drag = new Dragdealer('drag_'+container_id, {
      animationCallback: function(x, y) {
        // doing some cool stuff here
      },
      dragStartCallback: function(x, y) {
        console.log('drag start');
      },
      dragStopCallback: function(x, y) {
        console.log('drag stop');
      },
      steps: 2,
      speed: 0.50
    });
```

**Comment by skidding** [comment]
Are you testing with the latest Dragdealer version? This is the line that triggers the dragStart event: https://github.com/skidding/dragdealer/blob/master/src/dragdealer.js#L547

**Comment by thiagocoelho** [comment]
I'm using the lastest version, looks like those callbacks aren't implemented in this version :P

https://github.com/skidding/dragdealer/blob/0.9.8/src/dragdealer.js#L547

**Comment by skidding** [comment]
Right. You should be using the unreleased 0.9.9 version :P https://github.com/skidding/dragdealer/blob/master/src/dragdealer.js

**Comment by thiagocoelho** [comment]
Thank you @skidding 

Now I'm using the latest (master).

Everything working like a charm! :D

**Comment by skidding** [comment]
:cool:
