### ISSUE TITLE
Standalone basic example

### ISSUE THREAD

**Issue by talyellin** [skidding/dragdealer#98]
Is it possible to put an individual example on a page? Does dragdealer need all these dependencies (besides jquery)?

lib/jasmine.js
lib/jasmine-jsreporter.js
lib/jasmine-html.js
lib/jasmine-jquery.js

spec/helpers.js
spec/matchers.js
spec/optionsSpec.js
spec/draggingSpec.js
  
spec/touchDraggingSpec.js
  
spec/callbacksSpec.js
spec/apiSpec.js
spec/resizingSpec.js
spec/eventsSpec.js
spec/setup.js
spec/browser-runner.js

**Comment by skidding** [comment]
Yes. Dragdealer has no dependency, not even jQuery! Those libs are used for
testing.

On Tuesday, June 30, 2015, tal yellin <notifications@github.com> wrote:

> Is it possible to put an individual example on a page? Does dragdealer
> need all these dependencies (besides jquery)?
>
>
>
>
>
>
>
>
> 
>
> 
>
>
>
>
>
>  —
> Reply to this email directly or view it on GitHub
> <https://github.com/skidding/dragdealer/issues/98>.
>


-- 
Best regards,
Ovidiu Cherecheş
